[2019-02-21 11:58:00,621] WARN Client session timed out, have not heard from server in 16598ms for sessionid 0x1000c6938580002 (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:00,840] INFO Client session timed out, have not heard from server in 16598ms for sessionid 0x1000c6938580002, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:01,826] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=65) to node 1: java.io.IOException: Connection to 1 was disconnected before the response was read. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:01,826] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=12763) to node 0: java.io.IOException: Connection to 0 was disconnected before the response was read. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:01,832] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=12763)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 0 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:99)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:01,834] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=65)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 1 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:99)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:02,830] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:02,837] INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:02,851] WARN Unable to reconnect to ZooKeeper service, session 0x1000c6938580002 has expired (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:02,852] INFO Unable to reconnect to ZooKeeper service, session 0x1000c6938580002 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:02,855] INFO EventThread shut down for session: 0x1000c6938580002 (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:02,857] INFO [ZooKeeperClient] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2019-02-21 11:58:02,871] INFO [ZooKeeperClient] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2019-02-21 11:58:02,872] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@42a48628 (org.apache.zookeeper.ZooKeeper)
[2019-02-21 11:58:02,877] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:02,877] INFO Socket connection established to localhost/0:0:0:0:0:0:0:1:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:02,894] INFO Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2181, sessionid = 0x1000c693858000a, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:02,905] INFO Creating /brokers/ids/2 (is it secure? false) (kafka.zk.KafkaZkClient)
[2019-02-21 11:58:02,906] INFO Result of znode creation at /brokers/ids/2 is: OK (kafka.zk.KafkaZkClient)
[2019-02-21 11:58:02,907] INFO Registered broker 2 at path /brokers/ids/2 with addresses: ArrayBuffer(EndPoint(dhcp-231-038.eduroam.muni.cz,9094,ListenerName(PLAINTEXT),PLAINTEXT)) (kafka.zk.KafkaZkClient)
[2019-02-21 11:58:03,845] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.lang.IllegalStateException: No entry found for connection 1. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:03,846] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.lang.IllegalStateException: No entry found for connection 1
	at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:339)
	at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:143)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:03,847] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.lang.IllegalStateException: No entry found for connection 0. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:03,848] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.lang.IllegalStateException: No entry found for connection 0
	at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:339)
	at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:143)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:05,851] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.lang.IllegalStateException: No entry found for connection 1. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:05,852] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.lang.IllegalStateException: No entry found for connection 0. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:05,858] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.lang.IllegalStateException: No entry found for connection 1
	at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:339)
	at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:143)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:05,859] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.lang.IllegalStateException: No entry found for connection 0
	at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:339)
	at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:143)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:07,868] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.lang.IllegalStateException: No entry found for connection 1. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:07,869] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.lang.IllegalStateException: No entry found for connection 0. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:07,871] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.lang.IllegalStateException: No entry found for connection 1
	at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:339)
	at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:143)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:07,871] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.lang.IllegalStateException: No entry found for connection 0
	at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:339)
	at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:143)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:09,883] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.lang.IllegalStateException: No entry found for connection 0. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:09,883] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.lang.IllegalStateException: No entry found for connection 1. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:09,884] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.lang.IllegalStateException: No entry found for connection 0
	at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:339)
	at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:143)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:09,885] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.lang.IllegalStateException: No entry found for connection 1
	at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:339)
	at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:143)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:12,490] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.lang.IllegalStateException: No entry found for connection 1. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:12,490] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.lang.IllegalStateException: No entry found for connection 0. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:12,491] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.lang.IllegalStateException: No entry found for connection 1
	at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:339)
	at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:143)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:12,491] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.lang.IllegalStateException: No entry found for connection 0
	at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:339)
	at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:143)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:14,557] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:14,557] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:14,558] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:14,559] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:14,561] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:14,561] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:16,646] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:16,646] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:16,648] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:16,648] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:16,649] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:16,649] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:18,759] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:18,759] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:18,760] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:18,760] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:18,760] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:18,760] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:20,847] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:20,848] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:20,849] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:20,853] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:20,854] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:20,854] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:23,071] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:23,071] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:23,071] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:23,072] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:23,072] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:23,072] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:25,185] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:25,186] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:25,261] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:25,262] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:25,262] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:25,263] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:27,315] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:27,315] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:27,315] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:27,315] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:27,316] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:27,316] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:29,607] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:29,608] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:29,608] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:29,608] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:29,609] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:29,609] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:32,120] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:32,121] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:32,121] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:32,121] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:32,123] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:32,124] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:33,466] INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-02-21 11:58:33,504] INFO [KafkaServer id=2] shutting down (kafka.server.KafkaServer)
[2019-02-21 11:58:33,507] INFO [KafkaServer id=2] Starting controlled shutdown (kafka.server.KafkaServer)
[2019-02-21 11:58:33,519] WARN [KafkaServer id=2] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:33,520] WARN [KafkaServer id=2] Error during controlled shutdown, possibly because leader movement took longer than the configured controller.socket.timeout.ms and/or request.timeout.ms: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed. (kafka.server.KafkaServer)
[2019-02-21 11:58:34,185] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:34,185] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:34,186] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:34,188] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:34,188] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:34,189] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:36,279] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:36,279] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:36,280] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:36,280] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:36,280] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:36,282] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:38,480] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:38,480] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:38,480] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:38,480] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:38,481] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:38,482] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:38,521] WARN [KafkaServer id=2] Retrying controlled shutdown after the previous attempt failed... (kafka.server.KafkaServer)
[2019-02-21 11:58:38,747] WARN [KafkaServer id=2] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:38,747] WARN [KafkaServer id=2] Error during controlled shutdown, possibly because leader movement took longer than the configured controller.socket.timeout.ms and/or request.timeout.ms: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed. (kafka.server.KafkaServer)
[2019-02-21 11:58:39,053] INFO Unable to read additional data from server sessionid 0x1000c693858000a, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:40,489] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Connection to node 0 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:40,489] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1223002021, epoch=INITIAL) to node 0: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:40,490] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-28=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-3=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-5=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-4=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-43=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-10=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-25=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-0=(fetchOffset=13, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-7=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-37=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-40=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-22=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-4=(fetchOffset=126294, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-34=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-19=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-49=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-16=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-31=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-3=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-46=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-13=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1223002021, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:40,490] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Connection to node 1 (dhcp-231-038.eduroam.muni.cz/147.251.231.38:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-02-21 11:58:40,491] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=2027813006, epoch=INITIAL) to node 1: java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-02-21 11:58:40,491] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-17=(fetchOffset=27776, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-32=(fetchOffset=1844, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-4=(fetchOffset=12, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-47=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-14=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-44=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-29=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-4=(fetchOffset=2, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-telekom-1=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-5=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-11=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-41=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-26=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-23=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ups-1=(fetchOffset=8, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-3=(fetchOffset=6, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-ibm-2=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-8=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-38=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-4=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), auth_keys-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-20=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), company-usb-0=(fetchOffset=10, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-5=(fetchOffset=14348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-35=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0]), __consumer_offsets-2=(fetchOffset=5696, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=2027813006, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to dhcp-231-038.eduroam.muni.cz:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:94)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:192)
	at kafka.server.AbstractFetcherThread.kafka$server$AbstractFetcherThread$$processFetchRequest(AbstractFetcherThread.scala:274)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread$$anonfun$maybeFetch$1.apply(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
[2019-02-21 11:58:40,608] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:40,609] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-02-21 11:58:41,966] ERROR Error while writing to checkpoint file /tmp/xsilhar-kafka-3-2-logs/replication-offset-checkpoint (kafka.server.LogDirFailureChannel)
java.io.FileNotFoundException: /tmp/xsilhar-kafka-3-2-logs/replication-offset-checkpoint.tmp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:52)
	at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:50)
	at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:59)
	at kafka.server.ReplicaManager$$anonfun$checkpointHighWatermarks$2$$anonfun$apply$50.apply(ReplicaManager.scala:1404)
	at kafka.server.ReplicaManager$$anonfun$checkpointHighWatermarks$2$$anonfun$apply$50.apply(ReplicaManager.scala:1404)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.ReplicaManager$$anonfun$checkpointHighWatermarks$2.apply(ReplicaManager.scala:1404)
	at kafka.server.ReplicaManager$$anonfun$checkpointHighWatermarks$2.apply(ReplicaManager.scala:1401)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at kafka.server.ReplicaManager.checkpointHighWatermarks(ReplicaManager.scala:1401)
	at kafka.server.ReplicaManager$$anonfun$1.apply$mcV$sp(ReplicaManager.scala:248)
	at kafka.utils.KafkaScheduler$$anonfun$1.apply$mcV$sp(KafkaScheduler.scala:114)
	at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-21 11:58:41,968] INFO [ReplicaManager broker=2] Stopping serving replicas in dir /tmp/xsilhar-kafka-3-2-logs (kafka.server.ReplicaManager)
[2019-02-21 11:58:41,969] ERROR [ReplicaManager broker=2] Error while writing to highwatermark file in directory /tmp/xsilhar-kafka-3-2-logs (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.KafkaStorageException: Error while writing to checkpoint file /tmp/xsilhar-kafka-3-2-logs/replication-offset-checkpoint
Caused by: java.io.FileNotFoundException: /tmp/xsilhar-kafka-3-2-logs/replication-offset-checkpoint.tmp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:52)
	at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:50)
	at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:59)
	at kafka.server.ReplicaManager$$anonfun$checkpointHighWatermarks$2$$anonfun$apply$50.apply(ReplicaManager.scala:1404)
	at kafka.server.ReplicaManager$$anonfun$checkpointHighWatermarks$2$$anonfun$apply$50.apply(ReplicaManager.scala:1404)
	at scala.Option.foreach(Option.scala:257)
	at kafka.server.ReplicaManager$$anonfun$checkpointHighWatermarks$2.apply(ReplicaManager.scala:1404)
	at kafka.server.ReplicaManager$$anonfun$checkpointHighWatermarks$2.apply(ReplicaManager.scala:1401)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at kafka.server.ReplicaManager.checkpointHighWatermarks(ReplicaManager.scala:1401)
	at kafka.server.ReplicaManager$$anonfun$1.apply$mcV$sp(ReplicaManager.scala:248)
	at kafka.utils.KafkaScheduler$$anonfun$1.apply$mcV$sp(KafkaScheduler.scala:114)
	at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2019-02-21 11:58:41,980] INFO [ReplicaFetcherManager on broker 2] Removed fetcher for partitions Set(__consumer_offsets-22, company-ups-2, __consumer_offsets-30, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, company-usb-5, auth_keys-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, company-telekom-5, __consumer_offsets-46, company-ibm-0, __consumer_offsets-25, company-ups-3, __consumer_offsets-35, __consumer_offsets-41, company-usb-1, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, company-usb-0, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, company-telekom-4, __consumer_offsets-42, __consumer_offsets-3, company-ibm-3, __consumer_offsets-18, company-ibm-1, company-ibm-5, company-ups-5, __consumer_offsets-37, __consumer_offsets-15, company-telekom-2, __consumer_offsets-24, company-ups-4, company-usb-2, auth_keys-5, __consumer_offsets-38, __consumer_offsets-17, auth_keys-2, company-telekom-3, __consumer_offsets-48, auth_keys-3, __consumer_offsets-19, __consumer_offsets-11, company-ibm-4, company-telekom-1, __consumer_offsets-13, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, company-ibm-2, __consumer_offsets-14, company-usb-3, company-ups-1, auth_keys-1, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, company-ups-0, __consumer_offsets-12, company-telekom-0, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, company-usb-4, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, auth_keys-0, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaFetcherManager)
[2019-02-21 11:58:41,981] INFO [ReplicaAlterLogDirsManager on broker 2] Removed fetcher for partitions Set(__consumer_offsets-22, company-ups-2, __consumer_offsets-30, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, company-usb-5, auth_keys-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, company-telekom-5, __consumer_offsets-46, company-ibm-0, __consumer_offsets-25, company-ups-3, __consumer_offsets-35, __consumer_offsets-41, company-usb-1, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, company-usb-0, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, company-telekom-4, __consumer_offsets-42, __consumer_offsets-3, company-ibm-3, __consumer_offsets-18, company-ibm-1, company-ibm-5, company-ups-5, __consumer_offsets-37, __consumer_offsets-15, company-telekom-2, __consumer_offsets-24, company-ups-4, company-usb-2, auth_keys-5, __consumer_offsets-38, __consumer_offsets-17, auth_keys-2, company-telekom-3, __consumer_offsets-48, auth_keys-3, __consumer_offsets-19, __consumer_offsets-11, company-ibm-4, company-telekom-1, __consumer_offsets-13, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, company-ibm-2, __consumer_offsets-14, company-usb-3, company-ups-1, auth_keys-1, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, company-ups-0, __consumer_offsets-12, company-telekom-0, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, company-usb-4, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, auth_keys-0, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaAlterLogDirsManager)
[2019-02-21 11:58:42,018] INFO [ReplicaManager broker=2] Broker 2 stopped fetcher for partitions __consumer_offsets-22,company-ups-2,__consumer_offsets-30,__consumer_offsets-8,__consumer_offsets-21,__consumer_offsets-4,company-usb-5,auth_keys-4,__consumer_offsets-27,__consumer_offsets-7,__consumer_offsets-9,company-telekom-5,__consumer_offsets-46,company-ibm-0,__consumer_offsets-25,company-ups-3,__consumer_offsets-35,__consumer_offsets-41,company-usb-1,__consumer_offsets-33,__consumer_offsets-23,__consumer_offsets-49,__consumer_offsets-47,__consumer_offsets-16,company-usb-0,__consumer_offsets-28,__consumer_offsets-31,__consumer_offsets-36,company-telekom-4,__consumer_offsets-42,__consumer_offsets-3,company-ibm-3,__consumer_offsets-18,company-ibm-1,company-ibm-5,company-ups-5,__consumer_offsets-37,__consumer_offsets-15,company-telekom-2,__consumer_offsets-24,company-ups-4,company-usb-2,auth_keys-5,__consumer_offsets-38,__consumer_offsets-17,auth_keys-2,company-telekom-3,__consumer_offsets-48,auth_keys-3,__consumer_offsets-19,__consumer_offsets-11,company-ibm-4,company-telekom-1,__consumer_offsets-13,__consumer_offsets-2,__consumer_offsets-43,__consumer_offsets-6,company-ibm-2,__consumer_offsets-14,company-usb-3,company-ups-1,auth_keys-1,__consumer_offsets-20,__consumer_offsets-0,__consumer_offsets-44,__consumer_offsets-39,company-ups-0,__consumer_offsets-12,company-telekom-0,__consumer_offsets-45,__consumer_offsets-1,__consumer_offsets-5,__consumer_offsets-26,company-usb-4,__consumer_offsets-29,__consumer_offsets-34,__consumer_offsets-10,auth_keys-0,__consumer_offsets-32,__consumer_offsets-40 and stopped moving logs for partitions  because they are in the failed log directory /tmp/xsilhar-kafka-3-2-logs. (kafka.server.ReplicaManager)
[2019-02-21 11:58:42,019] INFO Stopping serving logs in dir /tmp/xsilhar-kafka-3-2-logs (kafka.log.LogManager)
[2019-02-21 11:58:42,027] ERROR Shutdown broker because all log dirs in /tmp/xsilhar-kafka-3-2-logs have failed (kafka.log.LogManager)
